// @ts-nocheck
import * as __fd_glob_45 from "../content/docs/security/trust-model.md?collection=docs"
import * as __fd_glob_44 from "../content/docs/security/overview.md?collection=docs"
import * as __fd_glob_43 from "../content/docs/security/audit-checklist.md?collection=docs"
import * as __fd_glob_42 from "../content/docs/troubleshooting/overview.md?collection=docs"
import * as __fd_glob_41 from "../content/docs/troubleshooting/common-issues.md?collection=docs"
import * as __fd_glob_40 from "../content/docs/smart-contracts/upgradeable-contracts.md?collection=docs"
import * as __fd_glob_39 from "../content/docs/smart-contracts/policy-vault.md?collection=docs"
import * as __fd_glob_38 from "../content/docs/smart-contracts/overview.md?collection=docs"
import * as __fd_glob_37 from "../content/docs/smart-contracts/icm-receiver.md?collection=docs"
import * as __fd_glob_36 from "../content/docs/smart-contracts/chainpe-registry.md?collection=docs"
import * as __fd_glob_35 from "../content/docs/merchants/registration.md?collection=docs"
import * as __fd_glob_34 from "../content/docs/merchants/receiving-payments.md?collection=docs"
import * as __fd_glob_33 from "../content/docs/merchants/policy-configuration.md?collection=docs"
import * as __fd_glob_32 from "../content/docs/merchants/overview.md?collection=docs"
import * as __fd_glob_31 from "../content/docs/sdk-reference/overview.md?collection=docs"
import * as __fd_glob_30 from "../content/docs/sdk-reference/chainpe-sdk.md?collection=docs"
import * as __fd_glob_29 from "../content/docs/sdk-reference/chainpe-ai-tools.md?collection=docs"
import * as __fd_glob_28 from "../content/docs/sdk-reference/chainpe-agent.md?collection=docs"
import * as __fd_glob_27 from "../content/docs/payment-flows/validation.md?collection=docs"
import * as __fd_glob_26 from "../content/docs/payment-flows/settlement.md?collection=docs"
import * as __fd_glob_25 from "../content/docs/payment-flows/overview.md?collection=docs"
import * as __fd_glob_24 from "../content/docs/payment-flows/initiation.md?collection=docs"
import * as __fd_glob_23 from "../content/docs/getting-started/quickstart.md?collection=docs"
import * as __fd_glob_22 from "../content/docs/getting-started/overview.md?collection=docs"
import * as __fd_glob_21 from "../content/docs/getting-started/installation.md?collection=docs"
import * as __fd_glob_20 from "../content/docs/getting-started/first-payment.md?collection=docs"
import * as __fd_glob_19 from "../content/docs/developers/sdk-setup.md?collection=docs"
import * as __fd_glob_18 from "../content/docs/developers/overview.md?collection=docs"
import * as __fd_glob_17 from "../content/docs/developers/ai-tools.md?collection=docs"
import * as __fd_glob_16 from "../content/docs/developers/agent-integration.md?collection=docs"
import * as __fd_glob_15 from "../content/docs/concepts/x402-protocol.md?collection=docs"
import * as __fd_glob_14 from "../content/docs/concepts/policy-vaults.md?collection=docs"
import * as __fd_glob_13 from "../content/docs/concepts/overview.md?collection=docs"
import * as __fd_glob_12 from "../content/docs/concepts/icm-cross-chain.md?collection=docs"
import * as __fd_glob_11 from "../content/docs/concepts/erc-8004-reputation.md?collection=docs"
import * as __fd_glob_10 from "../content/docs/architecture/system-diagram.md?collection=docs"
import * as __fd_glob_9 from "../content/docs/architecture/smart-contracts.md?collection=docs"
import * as __fd_glob_8 from "../content/docs/architecture/services.md?collection=docs"
import * as __fd_glob_7 from "../content/docs/architecture/overview.md?collection=docs"
import * as __fd_glob_6 from "../content/docs/api-reference/overview.md?collection=docs"
import * as __fd_glob_5 from "../content/docs/api-reference/indexer.md?collection=docs"
import * as __fd_glob_4 from "../content/docs/api-reference/facilitator.md?collection=docs"
import * as __fd_glob_3 from "../content/docs/introduction.md?collection=docs"
import * as __fd_glob_2 from "../content/docs/faq.md?collection=docs"
import * as __fd_glob_1 from "../content/docs/contributing.md?collection=docs"
import * as __fd_glob_0 from "../content/docs/changelog.md?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {}, {"changelog.md": __fd_glob_0, "contributing.md": __fd_glob_1, "faq.md": __fd_glob_2, "introduction.md": __fd_glob_3, "api-reference/facilitator.md": __fd_glob_4, "api-reference/indexer.md": __fd_glob_5, "api-reference/overview.md": __fd_glob_6, "architecture/overview.md": __fd_glob_7, "architecture/services.md": __fd_glob_8, "architecture/smart-contracts.md": __fd_glob_9, "architecture/system-diagram.md": __fd_glob_10, "concepts/erc-8004-reputation.md": __fd_glob_11, "concepts/icm-cross-chain.md": __fd_glob_12, "concepts/overview.md": __fd_glob_13, "concepts/policy-vaults.md": __fd_glob_14, "concepts/x402-protocol.md": __fd_glob_15, "developers/agent-integration.md": __fd_glob_16, "developers/ai-tools.md": __fd_glob_17, "developers/overview.md": __fd_glob_18, "developers/sdk-setup.md": __fd_glob_19, "getting-started/first-payment.md": __fd_glob_20, "getting-started/installation.md": __fd_glob_21, "getting-started/overview.md": __fd_glob_22, "getting-started/quickstart.md": __fd_glob_23, "payment-flows/initiation.md": __fd_glob_24, "payment-flows/overview.md": __fd_glob_25, "payment-flows/settlement.md": __fd_glob_26, "payment-flows/validation.md": __fd_glob_27, "sdk-reference/chainpe-agent.md": __fd_glob_28, "sdk-reference/chainpe-ai-tools.md": __fd_glob_29, "sdk-reference/chainpe-sdk.md": __fd_glob_30, "sdk-reference/overview.md": __fd_glob_31, "merchants/overview.md": __fd_glob_32, "merchants/policy-configuration.md": __fd_glob_33, "merchants/receiving-payments.md": __fd_glob_34, "merchants/registration.md": __fd_glob_35, "smart-contracts/chainpe-registry.md": __fd_glob_36, "smart-contracts/icm-receiver.md": __fd_glob_37, "smart-contracts/overview.md": __fd_glob_38, "smart-contracts/policy-vault.md": __fd_glob_39, "smart-contracts/upgradeable-contracts.md": __fd_glob_40, "troubleshooting/common-issues.md": __fd_glob_41, "troubleshooting/overview.md": __fd_glob_42, "security/audit-checklist.md": __fd_glob_43, "security/overview.md": __fd_glob_44, "security/trust-model.md": __fd_glob_45, });